name          'puppet-pydio'
version       '0.1.0'
source        'git://github.com/chriscowley/puppet-pydio.git'
author        'Chris Cowley'
license       'Apache License, Version 2.0'
summary       'Pydio'
description   'Put Your Data In Orbit'
project_page  'https://github.com/chriscowley/puppet-pydio'
dependency 'chriscowley/yumrepos'
dependency 'puppetlabs-apt', '>1.5.0'
dependency 'puppetlabs-mysql', '>2.2.3'
